### ISSUE TITLE
Metadaten anreichern

### ISSUE THREAD

**Issue by katrinleinweber** [TIBHannover/GeoEstimation#1]
Hallo @TIB-Visual-Analytics,

Bitte eine Repo-Description hinzufügen, sowie einige [Topics], die es auch im Rest von GitHub gibt.

Danke, und viele Grüße!
Katrin

[Topics]: https://blog.github.com/2017-01-31-introducing-topics/

**Comment by katrinleinweber** [comment]
Danke sehr :-)

**Comment by TIB-Visual-Analytics** [comment]
Kein Problem ;-)
