### ISSUE TITLE
can't find training data

### ISSUE THREAD

**Issue by YangBowenn** [TIBHannover/GeoEstimation#10]
hi, I can't find training data matchs 'mp16_places365.csv' from the link: http://multimedia-commons.s3-website-us-west-2.amazonaws.com/, could you help me, thanks!

**Comment by TIB-Visual-Analytics** [comment]
Hi, we have provided a [file](https://github.com/TIBHannover/GeoEstimation/releases/download/v1.0/mp16_urls.csv) containing the relative filenames and the corresponding URLs to download the images.

**Comment by YangBowenn** [comment]
Thank you very much!
