### ISSUE TITLE
download links for models doesn't work

### ISSUE THREAD

**Issue by chowwil** [TIBHannover/GeoEstimation#11]
Hi there I'm trying to download the models:

- resnet-v2-101.base_M-keras.h5

as well as trying to find the partitioning cells csv's:
"cells_50_5000.csv",
"cells_50_2000.csv",
"cells_50_1000.csv"

 for re-training the model, however the tensorflow model download links direct to "Not Found" and the downloader.py don't work from there.

Appreciate any help.
Thank you

**Comment by jtheiner** [comment]
Hi, it seems that you are using the `tf2` branch, which is no longer maintained and has basically been replaced with a PyTorch version.
We recommend using that re-implemented PyTorch version or in the case of reproducing the original paper results, using the Tensorflow V1 version.

**Comment by chowwil** [comment]
Gotcha thank you! Was there reasoning as to why tf2 is not workable with the GeoEstimation model? Was it just not compatible?

**Comment by jtheiner** [comment]
We tried to convert the original implementation to TensorFlow2 and ported the original network weights. However, we have achieved lower results. Without further investigation, we simply implemented a more lightweight version in PyTorch.
