### ISSUE TITLE
Get hotspot output

### ISSUE THREAD

**Issue by galewis2** [TIBHannover/GeoEstimation#19]
Hi, I see from https://labs.tib.eu/geoestimation/ that you can get hotspot outputs from predicted locations.

Is it possible to get that sort of output from either branch in this codebase, or could you point me towards the modifications needed to do so? I can do the GIS side of things, just not sure how to generate that output from torch.

Thanks!

**Comment by TIB-Visual-Analytics** [comment]
Hi, to construct the geographical heatmap you need the GPS coordinates of the geographical cells along with their probabilities. 

## GPS Coordinate

Please follow the instructions in the [requirements](https://github.com/TIBHannover/GeoEstimation#requirements) to download the partitioning files, e.g., ```resources/s2_cells/cells_50_1000.csv```, that contain the GPS coordinates of each cell. 

## Cell Probabilities

In our PyTorch implemtentation (master branch), the probabilities of each cell are denoted as ```yhats``` in this [function](https://github.com/TIBHannover/GeoEstimation/blob/136a85da2eb086f600a7ec7600264906390904e3/classification/train_base.py#L210)

## Visualization with Leaflet

Based on these inputs, we used leaflet to create the heatmap. Here are some useful links: 

- https://github.com/Leaflet/Leaflet.heat
- https://www.patrick-wied.at/static/heatmapjs/plugin-leaflet-layer.html


We hope this helps.

**Comment by galewis2** [comment]
Yes it does, thank-you!
