### ISSUE TITLE
Code for Scene Filtering

### ISSUE THREAD

**Issue by gmberton** [TIBHannover/GeoEstimation#20]
Thank you for the great repo!
Are you also planning to release the code to compute scene probabilities (scene filtering) for a given image? I'm referring to the module that you mention at Section 3.2 of your paper, which is needed to decide which images are kept or discarded for training.

**Comment by TIB-Visual-Analytics** [comment]
Thank you for your comment!

You can find the code for extracting scene probabilities in the [original_tf](https://github.com/TIBHannover/GeoEstimation/tree/original_tf) branch of the repository, specifically in the file [scene_classification.py](https://github.com/TIBHannover/GeoEstimation/blob/original_tf/scene_classification.py)

We have not provided the scene classification code for the PyTorch implementation in the master branch. However, if you prefer a PyTorch version, we kindly refer you to the [Places365 repository](https://github.com/CSAILVision/places365).

We hope this helps you!

**Comment by gmberton** [comment]
That was very useful!
If you want I can submit a PR to port that in pytorch in your repo, what do you think?

**Comment by gmberton** [comment]
Also, what are the differences between the (pytorch) code and the paper?
Should each of the dataset's subsets (nature, indoor, urban) be passed to a different net, so effectively there should be 3 of the models implemented in the code?

**Comment by eric-mb** [comment]
Thanks, a PR would be great of course, but please don't feel obligated to do that ;)

The pytorch code for the _base_ models should not differ from the paper. We only did not implement the _ISNs_ in PyTorch yet. 

Yes you are correct, the _ISNs_ are three networks that are trained separately on images that have a scene probability higher than $\tau_s > 0.3$ for the respective natural environment (nature, indoor, urban). The details can be found in Section 3.3 (paragraph: Individual Scene Networks (ISNs)) and Section 4 (paragraph: Scene Classification Parameters). We have already extracted the three scene probabilities for each training image. You can find them in the file [mp16_places365.csv](https://github.com/TIBHannover/GeoEstimation/releases/download/v1.0/mp16_places365.csv) in this release: https://github.com/TIBHannover/GeoEstimation/releases/tag/v1.0

Also note, that we initialized the network with the weights learned by the _base_ model when finetuning an _ISN_ as it saved training time and provided better results.

During inference, the Places365 model predicts the most likely environmental scene and the _ISN_ trained for this respective environment is used for geolocalization.


However, it is also worth noting that we tried different architectures including a more powerful EfficientNet in a follow-up [paper at WACV'22](https://openaccess.thecvf.com/content/WACV2022/papers/Theiner_Interpretable_Semantic_Photo_Geolocation_WACV_2022_paper.pdf) and already achieved better results (but we also did not try ISNs). You can find the repo here: https://github.com/jtheiner/semantic_geo_partitioning/tree/main/geo_classification

**Comment by gmberton** [comment]
Thanks for the thorough explanation and the reference!
I opened a PR to port the [scene_classification.py](https://github.com/TIBHannover/GeoEstimation/blob/original_tf/scene_classification.py) script in pytorch

**Comment by TIB-Visual-Analytics** [comment]
Thank you very much! :)
