### ISSUE TITLE
Could the demo accept user-provided images?

### ISSUE THREAD

**Issue by jakubklimek** [TIBHannover/GeoEstimation#4]
Cool demo, however, what I miss is the possibility to upload my own image to be guessed. Is this not available due to server performance issues or am I missing something?

**Comment by TIB-Visual-Analytics** [comment]
Hi Jakub,

the github demo just visualizes the precomputed paper results. However, we added a new web-tool where you can also upload own images. 

Please note that the Web-Tools should only be used for demonstration purposes. For larger scale calculations, please use the code provided in the repository.
