### ISSUE TITLE
caffe gpu installation for docker

### ISSUE THREAD

**Issue by jyjyj** [TIBHannover/GeoEstimation#7]
Hi, noticed that the provided Dockerfile doesn't have caffe for gpu (only for cpu). May I know if you guys have an optimal / preferred way of installing both tf and caffe for a gpu-enabled docker? I had this issue previously where I ended up with very large docker images (9++Gb). Thanks!

**Comment by TIB-Visual-Analytics** [comment]
We can only recommend to look for models trained with pytorch, keras, or tensorflow. For example you can find pytorch models for scene classification here: https://github.com/CSAILVision/places365

We have used the caffe model for our paper and need this dependency to reproduce the paper results.
