### ISSUE TITLE
Filtering out fake / cartoon-ish images

### ISSUE THREAD

**Issue by jyjyj** [TIBHannover/GeoEstimation#8]
Hi, in a project I'm working on, there is a possibility for me to receive images not of actual real scenes e.g. cartoons. They seem to be quite sporadic in terms of geoestimation results, with some producing quite high threshold scores as well. Would there be a recommended way to filter these out? Thank you!

**Comment by TIB-Visual-Analytics** [comment]
You can look at papers for image type classification like this one here: https://arxiv.org/abs/2001.06823v1

Please use other platforms like stackoverflow for questions like this, as this is not related to our repository
